import mongoose, { Document, Schema } from 'mongoose';

/**
 * Access / comp code for publishing a hotel listing.
 * Generated by an admin and sent to a host so they can post a listing without
 * paying (interim mechanism while the payment flow is unavailable).
 */
export const HOTEL_CODE_STATUSES = ['active', 'redeemed', 'revoked'] as const;
export type HotelCodeStatus = typeof HOTEL_CODE_STATUSES[number];

export interface IHotelListingCode extends Document {
  code: string;
  status: HotelCodeStatus;
  note?: string;
  createdBy?: mongoose.Types.ObjectId;
  redeemedBy?: mongoose.Types.ObjectId;
  redeemedHotel?: mongoose.Types.ObjectId;
  redeemedAt?: Date;
  expiresAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

const HotelListingCodeSchema: Schema = new Schema(
  {
    code: {
      type: String,
      required: true,
      unique: true,
      uppercase: true,
      trim: true,
      index: true,
    },
    status: {
      type: String,
      enum: { values: HOTEL_CODE_STATUSES, message: 'Invalid status: {VALUE}' },
      default: 'active',
      index: true,
    },
    note: { type: String, trim: true, maxlength: [200, 'Note cannot exceed 200 characters'] },
    createdBy: { type: Schema.Types.ObjectId, ref: 'User' },
    redeemedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    redeemedHotel: { type: Schema.Types.ObjectId, ref: 'Hotel' },
    redeemedAt: { type: Date },
    expiresAt: { type: Date },
  },
  {
    timestamps: true,
    toJSON: {
      transform(_doc: any, ret: any) {
        ret.id = ret._id;
        delete ret._id;
        delete ret.__v;
        return ret;
      },
    },
  }
);

/** True when the code can still be redeemed. */
HotelListingCodeSchema.methods.isRedeemable = function (this: IHotelListingCode): boolean {
  if (this.status !== 'active') return false;
  if (this.expiresAt && this.expiresAt.getTime() < Date.now()) return false;
  return true;
};

const HotelListingCode = mongoose.model<IHotelListingCode>('HotelListingCode', HotelListingCodeSchema);

export default HotelListingCode;
