/**
 * Shared city / country slug → canonical name lookup tables.
 * Keys are lowercase slugs (hyphens and underscores stripped) as they appear
 * in URL path segments. Values are display-ready canonical names.
 *
 * Used by the HTML enricher (URL-path extraction) and the normalizer
 * (address-splitting fallback). Covers all European countries + major
 * global destinations that appear on Balkan/international RE listings.
 */

export const CITY_SLUG_MAP: Record<string, string> = {
  // ── Albania ──────────────────────────────────────────────────────────────
  'tirana': 'Tirana', 'tirane': 'Tirana', 'tiranes': 'Tirana', 'tiranaa': 'Tirana',
  'durres': 'Durrës', 'durresi': 'Durrës', 'durresso': 'Durrës', 'durresdurres': 'Durrës',
  'vlore': 'Vlorë', 'vlora': 'Vlorë', 'vloravlore': 'Vlorë',
  'shkoder': 'Shkodër', 'shkodra': 'Shkodër',
  'elbasan': 'Elbasan', 'elbasani': 'Elbasan',
  'korce': 'Korçë', 'korca': 'Korçë',
  'fier': 'Fier', 'fieri': 'Fier',
  'berat': 'Berat', 'berati': 'Berat',
  'lushnje': 'Lushnjë', 'lushnja': 'Lushnjë',
  'pogradec': 'Pogradec',
  'gjirokaster': 'Gjirokastër', 'gjirokastra': 'Gjirokastër',
  'sarand': 'Sarandë', 'saranda': 'Sarandë',
  'kavaje': 'Kavajë', 'kavaja': 'Kavajë',
  'kamez': 'Kamëz', 'kamza': 'Kamëz',
  'lezhë': 'Lezhë', 'lezhe': 'Lezhë',
  'peshkopi': 'Peshkopi',
  'kukes': 'Kukës', 'kukesi': 'Kukës',
  'permet': 'Përmet',
  'tepelena': 'Tepelenë',
  'himara': 'Himarë',
  'shijak': 'Shijak',

  // ── Kosovo ────────────────────────────────────────────────────────────────
  'pristina': 'Pristina', 'prishtina': 'Pristina', 'prishtine': 'Pristina',
  'prizren': 'Prizren',
  'peja': 'Pejë', 'pec': 'Pejë',
  'gjakova': 'Gjakovë', 'dakovica': 'Gjakovë',
  'mitrovica': 'Mitrovicë', 'mitrovice': 'Mitrovicë',
  'ferizaj': 'Ferizaj', 'urosevac': 'Ferizaj',
  'gjilan': 'Gjilan', 'gnjilane': 'Gjilan',
  'podujevo': 'Podujevë',
  'vucitrn': 'Vushtrri',
  'rahovec': 'Rahovec',
  'decan': 'Deçan',
  'istog': 'Istog',
  'kamenica': 'Kamenicë',
  'lipjan': 'Lipjan',
  'malisheve': 'Malishevë',
  'obilic': 'Obiliq',
  'suva reka': 'Suva Rekë',
  'vitia': 'Viti',

  // ── North Macedonia ───────────────────────────────────────────────────────
  'skopje': 'Skopje', 'skoplje': 'Skopje',
  'bitola': 'Bitola', 'bitolj': 'Bitola',
  'ohrid': 'Ohrid',
  'tetovo': 'Tetovo', 'tetove': 'Tetovo',
  'kumanovo': 'Kumanovo',
  'gostivar': 'Gostivar',
  'strumica': 'Strumica',
  'veles': 'Veles',
  'stip': 'Štip',
  'kicevo': 'Kičevo',
  'struga': 'Struga',
  'radovis': 'Radoviš',
  'gevgelija': 'Gevgelija',
  'debar': 'Debar',
  'negotino': 'Negotino',
  'kavadarci': 'Kavadarci',
  'kocani': 'Kočani',
  'sveti nikole': 'Sveti Nikole',

  // ── Montenegro ────────────────────────────────────────────────────────────
  'podgorica': 'Podgorica',
  'niksic': 'Nikšić', 'niksici': 'Nikšić',
  'budva': 'Budva', 'budvanrivijera': 'Budva',
  'kotor': 'Kotor',
  'hercegnovi': 'Herceg Novi', 'herceg novi': 'Herceg Novi',
  'bar': 'Bar',
  'tivat': 'Tivat',
  'ulcinj': 'Ulcinj', 'ulqin': 'Ulcinj',
  'bijelo polje': 'Bijelo Polje', 'bijelo': 'Bijelo Polje',
  'pljevlja': 'Pljevlja',
  'berane': 'Berane',
  'rozaje': 'Rožaje',
  'cetinje': 'Cetinje',
  'plav': 'Plav',
  'zabljak': 'Žabljak',
  'kolasin': 'Kolašin',
  'petrovac': 'Petrovac na Moru',
  'sveti stefan': 'Sveti Stefan',
  'perast': 'Perast',

  // ── Bosnia and Herzegovina ────────────────────────────────────────────────
  'sarajevo': 'Sarajevo',
  'mostar': 'Mostar',
  'banjaluka': 'Banja Luka', 'banja luka': 'Banja Luka', 'banjaluke': 'Banja Luka',
  'tuzla': 'Tuzla',
  'zenica': 'Zenica',
  'bihac': 'Bihać',
  'bijeljina': 'Bijeljina',
  'doboj': 'Doboj',
  'trebinje': 'Trebinje',
  'zvornik': 'Zvornik',
  'travnik': 'Travnik',
  'gorazde': 'Goražde',
  'cazin': 'Cazin',
  'lukavac': 'Lukavac',
  'gradacac': 'Gradačac',
  'visoko': 'Visoko',
  'jajce': 'Jajce',
  'neum': 'Neum',
  'medjugorje': 'Međugorje',
  'srebrenica': 'Srebrenica',
  'pale': 'Pale',
  'ilidza': 'Ilidža',

  // ── Serbia ────────────────────────────────────────────────────────────────
  'beograd': 'Belgrade', 'belgrade': 'Belgrade',
  'novisad': 'Novi Sad', 'novi sad': 'Novi Sad',
  'nis': 'Niš', 'nish': 'Niš',
  'kragujevac': 'Kragujevac',
  'subotica': 'Subotica',
  'cacak': 'Čačak',
  'krusevac': 'Kruševac',
  'pancevo': 'Pančevo',
  'smederevo': 'Smederevo',
  'novi pazar': 'Novi Pazar', 'novipazar': 'Novi Pazar',
  'sabac': 'Šabac',
  'uzice': 'Užice',
  'valjevo': 'Valjevo',
  'leskovac': 'Leskovac',
  'pirot': 'Pirot',
  'zrenjanin': 'Zrenjanin',
  'sombor': 'Sombor',
  'prokuplje': 'Prokuplje',
  'vranje': 'Vranje',
  'pozarevac': 'Požarevac',
  'sremska mitrovica': 'Sremska Mitrovica',
  'kikinda': 'Kikinda',
  'bor': 'Bor',
  'zajecar': 'Zaječar',
  'zlatibor': 'Zlatibor',
  'kopaonik': 'Kopaonik',
  'vrnjacka banja': 'Vrnjačka Banja',
  'arandjelovac': 'Aranđelovac',
  'loznica': 'Loznica',

  // ── Croatia ───────────────────────────────────────────────────────────────
  'zagreb': 'Zagreb',
  'split': 'Split',
  'rijeka': 'Rijeka',
  'osijek': 'Osijek',
  'dubrovnik': 'Dubrovnik',
  'zadar': 'Zadar',
  'pula': 'Pula',
  'varazdin': 'Varaždin',
  'sibenik': 'Šibenik',
  'slavonski brod': 'Slavonski Brod', 'slavonskibrod': 'Slavonski Brod',
  'karlovac': 'Karlovac',
  'sisak': 'Sisak',
  'bjelovar': 'Bjelovar',
  'petrinja': 'Petrinja',
  'koprivnica': 'Koprivnica',
  'vukovar': 'Vukovar',
  'gospic': 'Gospić',
  'pazin': 'Pazin',
  'rovinj': 'Rovinj',
  'porec': 'Poreč',
  'umag': 'Umag',
  'crikvenica': 'Crikvenica',
  'makarska': 'Makarska',
  'omis': 'Omiš',
  'hvar': 'Hvar',
  'brac': 'Brač',
  'korcula': 'Korčula',
  'lošinj': 'Lošinj', 'losinj': 'Lošinj',
  'krk': 'Krk',
  'cavtat': 'Cavtat',
  'mali losinj': 'Mali Lošinj',
  'biograd': 'Biograd na Moru',

  // ── Slovenia ──────────────────────────────────────────────────────────────
  'ljubljana': 'Ljubljana',
  'maribor': 'Maribor',
  'celje': 'Celje',
  'kranj': 'Kranj',
  'koper': 'Koper',
  'velenje': 'Velenje',
  'novo mesto': 'Novo Mesto', 'novomesto': 'Novo Mesto',
  'murska sobota': 'Murska Sobota',
  'nova gorica': 'Nova Gorica', 'novagorica': 'Nova Gorica',
  'ptuj': 'Ptuj',
  'trbovlje': 'Trbovlje',
  'bled': 'Bled',
  'portoroz': 'Portorož', 'portorož': 'Portorož',
  'kranjska gora': 'Kranjska Gora',

  // ── Bulgaria ──────────────────────────────────────────────────────────────
  'sofia': 'Sofia', 'sofiya': 'Sofia',
  'plovdiv': 'Plovdiv',
  'varna': 'Varna',
  'burgas': 'Burgas',
  'stara zagora': 'Stara Zagora', 'starazagora': 'Stara Zagora',
  'ruse': 'Ruse',
  'pleven': 'Pleven',
  'sliven': 'Sliven',
  'dobrich': 'Dobrich',
  'shumen': 'Shumen',
  'pernik': 'Pernik',
  'haskovo': 'Haskovo',
  'yambol': 'Yambol',
  'pazardzhik': 'Pazardzhik',
  'blagoevgrad': 'Blagoevgrad',
  'vidin': 'Vidin',
  'montana': 'Montana',
  'lovech': 'Lovech',
  'kyustendil': 'Kyustendil',
  'targovishte': 'Targovishte',
  'razgrad': 'Razgrad',
  'silistra': 'Silistra',
  'nessebar': 'Nessebar',
  'sozopol': 'Sozopol',
  'sunny beach': 'Sunny Beach', 'sunnybeach': 'Sunny Beach',
  'golden sands': 'Golden Sands', 'goldensands': 'Golden Sands',
  'bansko': 'Bansko',
  'borovets': 'Borovets',
  'pamporovo': 'Pamporovo',

  // ── Romania ───────────────────────────────────────────────────────────────
  'bucharest': 'Bucharest', 'bucuresti': 'Bucharest', 'bucureşti': 'Bucharest',
  'cluj': 'Cluj-Napoca', 'clujnapoca': 'Cluj-Napoca',
  'timisoara': 'Timișoara', 'timişoara': 'Timișoara',
  'iasi': 'Iași', 'iaşi': 'Iași',
  'constanta': 'Constanța', 'constanţa': 'Constanța',
  'craiova': 'Craiova',
  'brasov': 'Brașov', 'braşov': 'Brașov',
  'galati': 'Galați', 'galaţi': 'Galați',
  'ploiesti': 'Ploiești', 'ploieşti': 'Ploiești',
  'oradea': 'Oradea',
  'braila': 'Brăila',
  'pitesti': 'Pitești',
  'arad': 'Arad',
  'sibiu': 'Sibiu',
  'bacau': 'Bacău',
  'targu mures': 'Târgu Mureș', 'targumures': 'Târgu Mureș',
  'baia mare': 'Baia Mare', 'baiamare': 'Baia Mare',
  'buzau': 'Buzău',
  'satu mare': 'Satu Mare', 'satumare': 'Satu Mare',
  'botosani': 'Botoșani',
  'piatra neamt': 'Piatra Neamț', 'piatraneamt': 'Piatra Neamț',
  'suceava': 'Suceava',
  'ramnicu valcea': 'Râmnicu Vâlcea',
  'drobeta turnu severin': 'Drobeta-Turnu Severin',
  'targu jiu': 'Târgu Jiu',
  'deva': 'Deva',
  'sinaia': 'Sinaia',
  'mamaia': 'Mamaia',
  'eforie': 'Eforie',
  'neptun': 'Neptun',

  // ── Greece ────────────────────────────────────────────────────────────────
  'athens': 'Athens', 'athina': 'Athens', 'athen': 'Athens', 'athènes': 'Athens',
  'thessaloniki': 'Thessaloniki', 'salonika': 'Thessaloniki',
  'patras': 'Patras',
  'heraklion': 'Heraklion', 'iraklion': 'Heraklion',
  'piraeus': 'Piraeus', 'pireaus': 'Piraeus',
  'larissa': 'Larissa',
  'volos': 'Volos',
  'ioannina': 'Ioannina',
  'chalkida': 'Chalkida',
  'serres': 'Serres',
  'alexandroupoli': 'Alexandroupoli',
  'xanthi': 'Xanthi',
  'kavala': 'Kavala',
  'drama': 'Drama',
  'katerini': 'Katerini',
  'corfu': 'Corfu', 'kerkyra': 'Corfu',
  'rhodes': 'Rhodes', 'rodos': 'Rhodes',
  'mykonos': 'Mykonos',
  'santorini': 'Santorini', 'thira': 'Santorini',
  'crete': 'Crete', 'kriti': 'Crete',
  'kos': 'Kos',
  'zakynthos': 'Zakynthos',
  'kefalonia': 'Kefalonia',
  'lefkada': 'Lefkada',
  'chania': 'Chania',
  'rethymno': 'Rethymno',
  'agios nikolaos': 'Agios Nikolaos',
  'glyfada': 'Glyfada',
  'maroussi': 'Maroussi',
  'kifisia': 'Kifisia',
  'paros': 'Paros',
  'naxos': 'Naxos',
  'samos': 'Samos',
  'halkidiki': 'Halkidiki',

  // ── Turkey ────────────────────────────────────────────────────────────────
  'istanbul': 'Istanbul', 'İstanbul': 'Istanbul',
  'ankara': 'Ankara',
  'izmir': 'Izmir', 'İzmir': 'Izmir',
  'bursa': 'Bursa',
  'adana': 'Adana',
  'antalya': 'Antalya',
  'konya': 'Konya',
  'gaziantep': 'Gaziantep',
  'mersin': 'Mersin',
  'diyarbakir': 'Diyarbakır',
  'kayseri': 'Kayseri',
  'eskisehir': 'Eskişehir',
  'denizli': 'Denizli',
  'samsun': 'Samsun',
  'trabzon': 'Trabzon',
  'malatya': 'Malatya',
  'alanya': 'Alanya',
  'side': 'Side',
  'bodrum': 'Bodrum',
  'marmaris': 'Marmaris',
  'fethiye': 'Fethiye',
  'dalaman': 'Dalaman',
  'kusadasi': 'Kuşadası',
  'cesme': 'Çeşme',
  'cappadocia': 'Cappadocia', 'kapadokya': 'Cappadocia',

  // ── Germany ───────────────────────────────────────────────────────────────
  'berlin': 'Berlin',
  'hamburg': 'Hamburg',
  'munich': 'Munich', 'münchen': 'Munich', 'muenchen': 'Munich',
  'cologne': 'Cologne', 'koeln': 'Cologne', 'köln': 'Cologne',
  'frankfurt': 'Frankfurt',
  'stuttgart': 'Stuttgart',
  'dusseldorf': 'Düsseldorf', 'düsseldorf': 'Düsseldorf',
  'dortmund': 'Dortmund',
  'essen': 'Essen',
  'leipzig': 'Leipzig',
  'Bremen': 'Bremen',
  'dresden': 'Dresden',
  'hannover': 'Hannover',
  'nuremberg': 'Nuremberg', 'nürnberg': 'Nuremberg',
  'duisburg': 'Duisburg',
  'bochum': 'Bochum',
  'wuppertal': 'Wuppertal',
  'bielefeld': 'Bielefeld',
  'mannheim': 'Mannheim',
  'bonn': 'Bonn',

  // ── Austria ───────────────────────────────────────────────────────────────
  'vienna': 'Vienna', 'wien': 'Vienna',
  'graz': 'Graz',
  'linz': 'Linz',
  'salzburg': 'Salzburg',
  'innsbruck': 'Innsbruck',
  'klagenfurt': 'Klagenfurt',
  'wels': 'Wels',

  // ── Switzerland ───────────────────────────────────────────────────────────
  'zurich': 'Zurich', 'zürich': 'Zurich',
  'geneva': 'Geneva', 'genève': 'Geneva', 'genf': 'Geneva',
  'basel': 'Basel',
  'bern': 'Bern',
  'lausanne': 'Lausanne',
  'lucerne': 'Lucerne', 'luzern': 'Lucerne',
  'winterthur': 'Winterthur',
  'st gallen': 'St. Gallen', 'stgallen': 'St. Gallen',

  // ── Italy ─────────────────────────────────────────────────────────────────
  'rome': 'Rome', 'roma': 'Rome',
  'milan': 'Milan', 'milano': 'Milan',
  'naples': 'Naples', 'napoli': 'Naples',
  'turin': 'Turin', 'torino': 'Turin',
  'palermo': 'Palermo',
  'genoa': 'Genoa', 'genova': 'Genoa',
  'bologna': 'Bologna',
  'florence': 'Florence', 'firenze': 'Florence',
  'bari': 'Bari',
  'catania': 'Catania',
  'venice': 'Venice', 'venezia': 'Venice',
  'verona': 'Verona',
  'trieste': 'Trieste',
  'messina': 'Messina',
  'padua': 'Padua', 'padova': 'Padua',
  'brescia': 'Brescia',
  'prato': 'Prato',
  'reggio calabria': 'Reggio Calabria',
  'modena': 'Modena',
  'reggio emilia': 'Reggio Emilia',
  'perugia': 'Perugia',
  'ravenna': 'Ravenna',
  'livorno': 'Livorno',
  'cagliari': 'Cagliari',
  'rimini': 'Rimini',
  'siena': 'Siena',
  'pisa': 'Pisa',
  'amalfi': 'Amalfi',
  'positano': 'Positano',
  'sardinia': 'Sardinia', 'sardegna': 'Sardinia',
  'sicily': 'Sicily', 'sicilia': 'Sicily',

  // ── France ────────────────────────────────────────────────────────────────
  'paris': 'Paris',
  'marseille': 'Marseille',
  'lyon': 'Lyon',
  'toulouse': 'Toulouse',
  'nice': 'Nice',
  'nantes': 'Nantes',
  'montpellier': 'Montpellier',
  'strasbourg': 'Strasbourg',
  'bordeaux': 'Bordeaux',
  'lille': 'Lille',
  'rennes': 'Rennes',
  'reims': 'Reims',
  'saint etienne': 'Saint-Étienne',
  'toulon': 'Toulon',
  'grenoble': 'Grenoble',
  'dijon': 'Dijon',
  'cannes': 'Cannes',
  'monaco': 'Monaco',
  'antibes': 'Antibes',
  'saint tropez': 'Saint-Tropez',
  'biarritz': 'Biarritz',

  // ── Spain ─────────────────────────────────────────────────────────────────
  'madrid': 'Madrid',
  'barcelona': 'Barcelona',
  'valencia': 'Valencia',
  'seville': 'Seville', 'sevilla': 'Seville',
  'zaragoza': 'Zaragoza',
  'malaga': 'Málaga', 'málaga': 'Málaga',
  'murcia': 'Murcia',
  'palma': 'Palma', 'palma de mallorca': 'Palma',
  'bilbao': 'Bilbao',
  'alicante': 'Alicante',
  'valladolid': 'Valladolid',
  'cordoba': 'Córdoba', 'córdoba': 'Córdoba',
  'vigo': 'Vigo',
  'granada': 'Granada',
  'elche': 'Elche',
  'oviedo': 'Oviedo',
  'santander': 'Santander',
  'marbella': 'Marbella',
  'ibiza': 'Ibiza',
  'tenerife': 'Tenerife',
  'gran canaria': 'Gran Canaria',
  'benidorm': 'Benidorm',
  'torrevieja': 'Torrevieja',

  // ── Portugal ──────────────────────────────────────────────────────────────
  'lisbon': 'Lisbon', 'lisboa': 'Lisbon',
  'porto': 'Porto',
  'braga': 'Braga',
  'setubal': 'Setúbal',
  'coimbra': 'Coimbra',
  'funchal': 'Funchal',
  'faro': 'Faro',
  'albufeira': 'Albufeira',
  'lagos': 'Lagos',
  'cascais': 'Cascais',
  'sintra': 'Sintra',
  'amadora': 'Amadora',
  'loule': 'Loulé',
  'portimao': 'Portimão',

  // ── Netherlands ───────────────────────────────────────────────────────────
  'amsterdam': 'Amsterdam',
  'rotterdam': 'Rotterdam',
  'the hague': 'The Hague', 'thehague': 'The Hague', 'denhaag': 'The Hague',
  'utrecht': 'Utrecht',
  'eindhoven': 'Eindhoven',
  'groningen': 'Groningen',
  'tilburg': 'Tilburg',
  'almere': 'Almere',
  'breda': 'Breda',
  'nijmegen': 'Nijmegen',
  'apeldoorn': 'Apeldoorn',
  'haarlem': 'Haarlem',
  'arnhem': 'Arnhem',
  'zaanstad': 'Zaanstad',

  // ── Belgium ───────────────────────────────────────────────────────────────
  'brussels': 'Brussels', 'bruxelles': 'Brussels', 'brussel': 'Brussels',
  'antwerp': 'Antwerp', 'antwerpen': 'Antwerp', 'anvers': 'Antwerp',
  'ghent': 'Ghent', 'gent': 'Ghent',
  'bruges': 'Bruges', 'brugge': 'Bruges',
  'liège': 'Liège', 'liege': 'Liège',
  'namur': 'Namur',
  'leuven': 'Leuven',

  // ── Poland ────────────────────────────────────────────────────────────────
  'warsaw': 'Warsaw', 'warszawa': 'Warsaw',
  'krakow': 'Kraków', 'kraków': 'Kraków', 'cracow': 'Kraków',
  'lodz': 'Łódź', 'łódź': 'Łódź',
  'wroclaw': 'Wrocław', 'wrocław': 'Wrocław',
  'poznan': 'Poznań', 'poznań': 'Poznań',
  'gdansk': 'Gdańsk', 'gdańsk': 'Gdańsk',
  'szczecin': 'Szczecin',
  'bydgoszcz': 'Bydgoszcz',
  'lublin': 'Lublin',
  'katowice': 'Katowice',
  'bialystok': 'Białystok',

  // ── Czech Republic ────────────────────────────────────────────────────────
  'prague': 'Prague', 'praha': 'Prague',
  'brno': 'Brno',
  'ostrava': 'Ostrava',
  'pilsen': 'Pilsen', 'plzen': 'Plzeň', 'plzeň': 'Plzeň',
  'liberec': 'Liberec',
  'olomouc': 'Olomouc',

  // ── Hungary ───────────────────────────────────────────────────────────────
  'budapest': 'Budapest',
  'debrecen': 'Debrecen',
  'szeged': 'Szeged',
  'miskolc': 'Miskolc',
  'pecs': 'Pécs', 'pécs': 'Pécs',
  'gyor': 'Győr', 'győr': 'Győr',
  'nyiregyhaza': 'Nyíregyháza',
  'kecskemet': 'Kecskemét',
  'balaton': 'Lake Balaton',

  // ── Slovakia ──────────────────────────────────────────────────────────────
  'bratislava': 'Bratislava',
  'kosice': 'Košice', 'košice': 'Košice',
  'presov': 'Prešov',
  'zilina': 'Žilina',
  'nitra': 'Nitra',
  'banska bystrica': 'Banská Bystrica',

  // ── United Kingdom ────────────────────────────────────────────────────────
  'london': 'London',
  'birmingham': 'Birmingham',
  'manchester': 'Manchester',
  'glasgow': 'Glasgow',
  'liverpool': 'Liverpool',
  'leeds': 'Leeds',
  'sheffield': 'Sheffield',
  'edinburgh': 'Edinburgh',
  'bristol': 'Bristol',
  'cardiff': 'Cardiff',
  'leicester': 'Leicester',
  'coventry': 'Coventry',
  'bradford': 'Bradford',
  'belfast': 'Belfast',
  'nottingham': 'Nottingham',
  'kingston': 'Kingston upon Thames',
  'southampton': 'Southampton',
  'cambridge': 'Cambridge',
  'oxford': 'Oxford',

  // ── Ireland ───────────────────────────────────────────────────────────────
  'dublin': 'Dublin',
  'cork': 'Cork',
  'limerick': 'Limerick',
  'galway': 'Galway',
  'waterford': 'Waterford',

  // ── Nordic Countries ──────────────────────────────────────────────────────
  'stockholm': 'Stockholm',
  'gothenburg': 'Gothenburg', 'göteborg': 'Gothenburg',
  'malmo': 'Malmö', 'malmö': 'Malmö',
  'oslo': 'Oslo',
  'bergen': 'Bergen',
  'trondheim': 'Trondheim',
  'stavanger': 'Stavanger',
  'copenhagen': 'Copenhagen', 'københavn': 'Copenhagen',
  'aarhus': 'Aarhus',
  'odense': 'Odense',
  'helsinki': 'Helsinki',
  'tampere': 'Tampere',
  'turku': 'Turku',
  'reykjavik': 'Reykjavik',

  // ── Eastern Europe ────────────────────────────────────────────────────────
  'kyiv': 'Kyiv', 'kiev': 'Kyiv',
  'kharkiv': 'Kharkiv',
  'odessa': 'Odessa',
  'lviv': 'Lviv',
  'dnipro': 'Dnipro',
  'minsk': 'Minsk',
  'chisinau': 'Chișinău', 'chișinău': 'Chișinău',
  'vilnius': 'Vilnius',
  'riga': 'Riga',
  'tallinn': 'Tallinn',
  'moscow': 'Moscow', 'moskva': 'Moscow',
  'saint petersburg': 'Saint Petersburg', 'saintpetersburg': 'Saint Petersburg',

  // ── Cyprus ────────────────────────────────────────────────────────────────
  'nicosia': 'Nicosia', 'lefkosia': 'Nicosia',
  'limassol': 'Limassol', 'lemesos': 'Limassol',
  'larnaca': 'Larnaca',
  'paphos': 'Paphos',
  'famagusta': 'Famagusta',
  'protaras': 'Protaras',
  'ayia napa': 'Ayia Napa', 'ayianapa': 'Ayia Napa',

  // ── Malta ─────────────────────────────────────────────────────────────────
  'valletta': 'Valletta',
  'sliema': 'Sliema',
  'st julians': 'St. Julian\'s', 'stjulians': 'St. Julian\'s',

  // ── UAE / Middle East ─────────────────────────────────────────────────────
  'dubai': 'Dubai',
  'abu dhabi': 'Abu Dhabi', 'abudhabi': 'Abu Dhabi',
  'sharjah': 'Sharjah',
  'riyadh': 'Riyadh',
  'doha': 'Doha',
  'beirut': 'Beirut',
  'amman': 'Amman',

  // ── United States ─────────────────────────────────────────────────────────
  'new york': 'New York', 'newyork': 'New York', 'nyc': 'New York',
  'los angeles': 'Los Angeles', 'losangeles': 'Los Angeles', 'la': 'Los Angeles',
  'chicago': 'Chicago',
  'houston': 'Houston',
  'phoenix': 'Phoenix',
  'philadelphia': 'Philadelphia',
  'san antonio': 'San Antonio',
  'san diego': 'San Diego',
  'dallas': 'Dallas',
  'san jose': 'San Jose',
  'miami': 'Miami',
  'atlanta': 'Atlanta',
  'boston': 'Boston',
  'seattle': 'Seattle',
  'denver': 'Denver',
  'las vegas': 'Las Vegas',
  'washington': 'Washington D.C.',
  'nashville': 'Nashville',
  'orlando': 'Orlando',

  // ── Canada ────────────────────────────────────────────────────────────────
  'toronto': 'Toronto',
  'montreal': 'Montreal', 'montréal': 'Montreal',
  'vancouver': 'Vancouver',
  'calgary': 'Calgary',
  'edmonton': 'Edmonton',
  'ottawa': 'Ottawa',
  'winnipeg': 'Winnipeg',
  'quebec city': 'Quebec City',

  // ── Australia ─────────────────────────────────────────────────────────────
  'sydney': 'Sydney',
  'melbourne': 'Melbourne',
  'brisbane': 'Brisbane',
  'perth': 'Perth',
  'adelaide': 'Adelaide',
  'canberra': 'Canberra',
  'gold coast': 'Gold Coast',
};

export const COUNTRY_SLUG_MAP: Record<string, string> = {
  // ── Balkan ────────────────────────────────────────────────────────────────
  'albania': 'Albania', 'al': 'Albania', 'shqiperia': 'Albania', 'shqiperi': 'Albania', 'shqiperise': 'Albania',
  'kosovo': 'Kosovo', 'kosova': 'Kosovo', 'ks': 'Kosovo',
  'northmacedonia': 'North Macedonia', 'macedonia': 'North Macedonia', 'mk': 'North Macedonia', 'makedonija': 'North Macedonia',
  'montenegro': 'Montenegro', 'crnagora': 'Montenegro', 'me': 'Montenegro',
  'bosniaandherzegovina': 'Bosnia and Herzegovina', 'bih': 'Bosnia and Herzegovina', 'ba': 'Bosnia and Herzegovina', 'bosnaihercegovina': 'Bosnia and Herzegovina',
  'serbia': 'Serbia', 'srbija': 'Serbia', 'rs': 'Serbia',
  'croatia': 'Croatia', 'hrvatska': 'Croatia', 'hr': 'Croatia',
  'slovenia': 'Slovenia', 'slovenija': 'Slovenia', 'si': 'Slovenia',
  // ── Central Europe ────────────────────────────────────────────────────────
  'bulgaria': 'Bulgaria', 'bulgarija': 'Bulgaria', 'bg': 'Bulgaria', 'balgariya': 'Bulgaria',
  'romania': 'Romania', 'ro': 'Romania', 'rumunija': 'Romania',
  'greece': 'Greece', 'ellada': 'Greece', 'gr': 'Greece', 'grcka': 'Greece', 'hellas': 'Greece',
  'hungary': 'Hungary', 'magyarorszag': 'Hungary', 'hu': 'Hungary', 'madjarska': 'Hungary',
  'czech': 'Czech Republic', 'czechrepublic': 'Czech Republic', 'czechia': 'Czech Republic', 'cz': 'Czech Republic',
  'slovakia': 'Slovakia', 'slovensko': 'Slovakia', 'sk': 'Slovakia',
  'poland': 'Poland', 'polska': 'Poland', 'pl': 'Poland',
  'austria': 'Austria', 'osterreich': 'Austria', 'at': 'Austria',
  'switzerland': 'Switzerland', 'schweiz': 'Switzerland', 'suisse': 'Switzerland', 'ch': 'Switzerland',
  // ── Western Europe ────────────────────────────────────────────────────────
  'germany': 'Germany', 'deutschland': 'Germany', 'de': 'Germany',
  'france': 'France', 'fr': 'France', 'frankreich': 'France',
  'italy': 'Italy', 'italia': 'Italy', 'it': 'Italy',
  'spain': 'Spain', 'espana': 'Spain', 'españa': 'Spain', 'es': 'Spain',
  'portugal': 'Portugal', 'pt': 'Portugal',
  'netherlands': 'Netherlands', 'nederland': 'Netherlands', 'nl': 'Netherlands', 'holland': 'Netherlands',
  'belgium': 'Belgium', 'belgique': 'Belgium', 'belgie': 'Belgium', 'be': 'Belgium',
  'luxembourg': 'Luxembourg', 'lu': 'Luxembourg',
  'unitedkingdom': 'United Kingdom', 'uk': 'United Kingdom', 'gb': 'United Kingdom', 'greatbritain': 'United Kingdom', 'england': 'United Kingdom',
  'ireland': 'Ireland', 'ie': 'Ireland', 'eire': 'Ireland',
  'monaco': 'Monaco', 'mc': 'Monaco',
  'liechtenstein': 'Liechtenstein', 'li': 'Liechtenstein',
  // ── Nordic ────────────────────────────────────────────────────────────────
  'sweden': 'Sweden', 'sverige': 'Sweden', 'se': 'Sweden',
  'norway': 'Norway', 'norge': 'Norway', 'no': 'Norway',
  'denmark': 'Denmark', 'danmark': 'Denmark', 'dk': 'Denmark',
  'finland': 'Finland', 'suomi': 'Finland', 'fi': 'Finland',
  'iceland': 'Iceland', 'island': 'Iceland', 'is': 'Iceland',
  // ── Eastern Europe ────────────────────────────────────────────────────────
  'ukraine': 'Ukraine', 'ukraina': 'Ukraine', 'ua': 'Ukraine',
  'russia': 'Russia', 'rossiya': 'Russia', 'ru': 'Russia',
  'belarus': 'Belarus', 'byelarus': 'Belarus', 'by': 'Belarus',
  'moldova': 'Moldova', 'md': 'Moldova',
  'lithuania': 'Lithuania', 'lietuva': 'Lithuania', 'lt': 'Lithuania',
  'latvia': 'Latvia', 'latvija': 'Latvia', 'lv': 'Latvia',
  'estonia': 'Estonia', 'eesti': 'Estonia', 'ee': 'Estonia',
  // ── Mediterranean / Middle East ───────────────────────────────────────────
  'turkey': 'Turkey', 'turkiye': 'Turkey', 'türkiye': 'Turkey', 'tr': 'Turkey',
  'cyprus': 'Cyprus', 'kibris': 'Cyprus', 'cy': 'Cyprus',
  'malta': 'Malta', 'mt': 'Malta',
  'uae': 'UAE', 'unitedarabemirates': 'UAE', 'ae': 'UAE', 'emirates': 'UAE',
  'saudiarabia': 'Saudi Arabia', 'sa': 'Saudi Arabia',
  'qatar': 'Qatar', 'qa': 'Qatar',
  'lebanon': 'Lebanon', 'lb': 'Lebanon',
  'jordan': 'Jordan', 'jo': 'Jordan',
  'israel': 'Israel', 'il': 'Israel',
  // ── Americas ──────────────────────────────────────────────────────────────
  'unitedstates': 'United States', 'usa': 'United States', 'us': 'United States',
  'canada': 'Canada', 'ca': 'Canada',
  // ── Oceania ───────────────────────────────────────────────────────────────
  'australia': 'Australia', 'au': 'Australia',
  'newzealand': 'New Zealand', 'nz': 'New Zealand',
};

/**
 * Maps every city slug (same keys as CITY_SLUG_MAP) to its canonical country name.
 * Used by the normalizer to infer country from city when source data omits it.
 */
export const CITY_TO_COUNTRY_MAP: Record<string, string> = {
  // ── Albania ───────────────────────────────────────────────────────────────
  'tirana': 'Albania', 'tirane': 'Albania', 'tiranes': 'Albania', 'tiranaa': 'Albania',
  'durres': 'Albania', 'durresi': 'Albania', 'durresso': 'Albania', 'durresdurres': 'Albania',
  'vlore': 'Albania', 'vlora': 'Albania', 'vloravlore': 'Albania',
  'shkoder': 'Albania', 'shkodra': 'Albania',
  'elbasan': 'Albania', 'elbasani': 'Albania',
  'korce': 'Albania', 'korca': 'Albania',
  'fier': 'Albania', 'fieri': 'Albania',
  'berat': 'Albania', 'berati': 'Albania',
  'lushnje': 'Albania', 'lushnja': 'Albania',
  'pogradec': 'Albania',
  'gjirokaster': 'Albania', 'gjirokastra': 'Albania',
  'sarand': 'Albania', 'saranda': 'Albania',
  'kavaje': 'Albania', 'kavaja': 'Albania',
  'kamez': 'Albania', 'kamza': 'Albania',
  'lezhë': 'Albania', 'lezhe': 'Albania',
  'peshkopi': 'Albania',
  'kukes': 'Albania', 'kukesi': 'Albania',
  'permet': 'Albania', 'tepelena': 'Albania', 'himara': 'Albania', 'shijak': 'Albania',

  // ── Kosovo ────────────────────────────────────────────────────────────────
  'pristina': 'Kosovo', 'prishtina': 'Kosovo', 'prishtine': 'Kosovo',
  'prizren': 'Kosovo',
  'peja': 'Kosovo', 'pec': 'Kosovo',
  'gjakova': 'Kosovo', 'dakovica': 'Kosovo',
  'mitrovica': 'Kosovo', 'mitrovice': 'Kosovo',
  'ferizaj': 'Kosovo', 'urosevac': 'Kosovo',
  'gjilan': 'Kosovo', 'gnjilane': 'Kosovo',
  'podujevo': 'Kosovo', 'vucitrn': 'Kosovo', 'rahovec': 'Kosovo',
  'decan': 'Kosovo', 'istog': 'Kosovo', 'kamenica': 'Kosovo',
  'lipjan': 'Kosovo', 'malisheve': 'Kosovo', 'obilic': 'Kosovo',
  'suva reka': 'Kosovo', 'vitia': 'Kosovo',

  // ── North Macedonia ───────────────────────────────────────────────────────
  'skopje': 'North Macedonia', 'skoplje': 'North Macedonia',
  'bitola': 'North Macedonia', 'bitolj': 'North Macedonia',
  'ohrid': 'North Macedonia',
  'tetovo': 'North Macedonia', 'tetove': 'North Macedonia',
  'kumanovo': 'North Macedonia', 'gostivar': 'North Macedonia',
  'strumica': 'North Macedonia', 'veles': 'North Macedonia',
  'stip': 'North Macedonia', 'kicevo': 'North Macedonia',
  'struga': 'North Macedonia', 'radovis': 'North Macedonia',
  'gevgelija': 'North Macedonia', 'debar': 'North Macedonia',
  'negotino': 'North Macedonia', 'kavadarci': 'North Macedonia',
  'kocani': 'North Macedonia', 'sveti nikole': 'North Macedonia',

  // ── Montenegro ────────────────────────────────────────────────────────────
  'podgorica': 'Montenegro',
  'niksic': 'Montenegro', 'niksici': 'Montenegro',
  'budva': 'Montenegro', 'budvanrivijera': 'Montenegro',
  'kotor': 'Montenegro',
  'hercegnovi': 'Montenegro', 'herceg novi': 'Montenegro',
  'bar': 'Montenegro', 'tivat': 'Montenegro', 'ulcinj': 'Montenegro', 'ulqin': 'Montenegro',
  'bijelo polje': 'Montenegro', 'bijelo': 'Montenegro',
  'pljevlja': 'Montenegro', 'berane': 'Montenegro', 'rozaje': 'Montenegro',
  'cetinje': 'Montenegro', 'plav': 'Montenegro', 'zabljak': 'Montenegro',
  'kolasin': 'Montenegro', 'petrovac': 'Montenegro',
  'sveti stefan': 'Montenegro', 'perast': 'Montenegro',

  // ── Bosnia and Herzegovina ────────────────────────────────────────────────
  'sarajevo': 'Bosnia and Herzegovina', 'mostar': 'Bosnia and Herzegovina',
  'banjaluka': 'Bosnia and Herzegovina', 'banja luka': 'Bosnia and Herzegovina', 'banjaluke': 'Bosnia and Herzegovina',
  'tuzla': 'Bosnia and Herzegovina', 'zenica': 'Bosnia and Herzegovina',
  'bihac': 'Bosnia and Herzegovina', 'bijeljina': 'Bosnia and Herzegovina',
  'doboj': 'Bosnia and Herzegovina', 'trebinje': 'Bosnia and Herzegovina',
  'zvornik': 'Bosnia and Herzegovina', 'travnik': 'Bosnia and Herzegovina',
  'gorazde': 'Bosnia and Herzegovina', 'cazin': 'Bosnia and Herzegovina',
  'lukavac': 'Bosnia and Herzegovina', 'gradacac': 'Bosnia and Herzegovina',
  'visoko': 'Bosnia and Herzegovina', 'jajce': 'Bosnia and Herzegovina',
  'neum': 'Bosnia and Herzegovina', 'medjugorje': 'Bosnia and Herzegovina',
  'srebrenica': 'Bosnia and Herzegovina', 'pale': 'Bosnia and Herzegovina',
  'ilidza': 'Bosnia and Herzegovina',

  // ── Serbia ────────────────────────────────────────────────────────────────
  'beograd': 'Serbia', 'belgrade': 'Serbia',
  'novisad': 'Serbia', 'novi sad': 'Serbia',
  'nis': 'Serbia', 'nish': 'Serbia',
  'kragujevac': 'Serbia', 'subotica': 'Serbia', 'cacak': 'Serbia',
  'krusevac': 'Serbia', 'pancevo': 'Serbia', 'smederevo': 'Serbia',
  'novi pazar': 'Serbia', 'novipazar': 'Serbia',
  'sabac': 'Serbia', 'uzice': 'Serbia', 'valjevo': 'Serbia',
  'leskovac': 'Serbia', 'pirot': 'Serbia', 'zrenjanin': 'Serbia',
  'sombor': 'Serbia', 'prokuplje': 'Serbia', 'vranje': 'Serbia',
  'pozarevac': 'Serbia', 'sremska mitrovica': 'Serbia',
  'kikinda': 'Serbia', 'bor': 'Serbia', 'zajecar': 'Serbia',
  'zlatibor': 'Serbia', 'kopaonik': 'Serbia',
  'vrnjacka banja': 'Serbia', 'arandjelovac': 'Serbia', 'loznica': 'Serbia',

  // ── Croatia ───────────────────────────────────────────────────────────────
  'zagreb': 'Croatia', 'split': 'Croatia', 'rijeka': 'Croatia',
  'osijek': 'Croatia', 'dubrovnik': 'Croatia', 'zadar': 'Croatia',
  'pula': 'Croatia', 'varazdin': 'Croatia', 'sibenik': 'Croatia',
  'slavonski brod': 'Croatia', 'slavonskibrod': 'Croatia',
  'karlovac': 'Croatia', 'sisak': 'Croatia', 'bjelovar': 'Croatia',
  'petrinja': 'Croatia', 'koprivnica': 'Croatia', 'vukovar': 'Croatia',
  'gospic': 'Croatia', 'pazin': 'Croatia', 'rovinj': 'Croatia',
  'porec': 'Croatia', 'umag': 'Croatia', 'crikvenica': 'Croatia',
  'makarska': 'Croatia', 'omis': 'Croatia', 'hvar': 'Croatia',
  'brac': 'Croatia', 'korcula': 'Croatia', 'lošinj': 'Croatia', 'losinj': 'Croatia',
  'krk': 'Croatia', 'cavtat': 'Croatia', 'mali losinj': 'Croatia',
  'biograd': 'Croatia',

  // ── Slovenia ──────────────────────────────────────────────────────────────
  'ljubljana': 'Slovenia', 'maribor': 'Slovenia', 'celje': 'Slovenia',
  'kranj': 'Slovenia', 'koper': 'Slovenia', 'velenje': 'Slovenia',
  'novo mesto': 'Slovenia', 'novomesto': 'Slovenia',
  'murska sobota': 'Slovenia', 'nova gorica': 'Slovenia', 'novagorica': 'Slovenia',
  'ptuj': 'Slovenia', 'trbovlje': 'Slovenia', 'bled': 'Slovenia',
  'portoroz': 'Slovenia', 'portorož': 'Slovenia', 'kranjska gora': 'Slovenia',

  // ── Bulgaria ──────────────────────────────────────────────────────────────
  'sofia': 'Bulgaria', 'sofiya': 'Bulgaria',
  'plovdiv': 'Bulgaria', 'varna': 'Bulgaria', 'burgas': 'Bulgaria',
  'stara zagora': 'Bulgaria', 'starazagora': 'Bulgaria',
  'ruse': 'Bulgaria', 'pleven': 'Bulgaria', 'sliven': 'Bulgaria',
  'dobrich': 'Bulgaria', 'shumen': 'Bulgaria', 'pernik': 'Bulgaria',
  'haskovo': 'Bulgaria', 'yambol': 'Bulgaria', 'pazardzhik': 'Bulgaria',
  'blagoevgrad': 'Bulgaria', 'vidin': 'Bulgaria', 'montana': 'Bulgaria',
  'lovech': 'Bulgaria', 'kyustendil': 'Bulgaria', 'targovishte': 'Bulgaria',
  'razgrad': 'Bulgaria', 'silistra': 'Bulgaria', 'nessebar': 'Bulgaria',
  'sozopol': 'Bulgaria', 'sunny beach': 'Bulgaria', 'sunnybeach': 'Bulgaria',
  'golden sands': 'Bulgaria', 'goldensands': 'Bulgaria',
  'bansko': 'Bulgaria', 'borovets': 'Bulgaria', 'pamporovo': 'Bulgaria',

  // ── Romania ───────────────────────────────────────────────────────────────
  'bucharest': 'Romania', 'bucuresti': 'Romania', 'bucureşti': 'Romania',
  'cluj': 'Romania', 'clujnapoca': 'Romania',
  'timisoara': 'Romania', 'timişoara': 'Romania',
  'iasi': 'Romania', 'iaşi': 'Romania',
  'constanta': 'Romania', 'constanţa': 'Romania',
  'craiova': 'Romania', 'brasov': 'Romania', 'braşov': 'Romania',
  'galati': 'Romania', 'galaţi': 'Romania',
  'ploiesti': 'Romania', 'ploieşti': 'Romania',
  'oradea': 'Romania', 'braila': 'Romania', 'pitesti': 'Romania',
  'arad': 'Romania', 'sibiu': 'Romania', 'bacau': 'Romania',
  'targu mures': 'Romania', 'targumures': 'Romania',
  'baia mare': 'Romania', 'baiamare': 'Romania',
  'buzau': 'Romania', 'satu mare': 'Romania', 'satumare': 'Romania',
  'botosani': 'Romania', 'piatra neamt': 'Romania', 'piatraneamt': 'Romania',
  'suceava': 'Romania', 'ramnicu valcea': 'Romania',
  'drobeta turnu severin': 'Romania', 'targu jiu': 'Romania',
  'deva': 'Romania', 'sinaia': 'Romania', 'mamaia': 'Romania',
  'eforie': 'Romania', 'neptun': 'Romania',

  // ── Greece ────────────────────────────────────────────────────────────────
  'athens': 'Greece', 'athina': 'Greece', 'athen': 'Greece', 'athènes': 'Greece',
  'thessaloniki': 'Greece', 'salonika': 'Greece',
  'patras': 'Greece', 'heraklion': 'Greece', 'iraklion': 'Greece',
  'piraeus': 'Greece', 'pireaus': 'Greece',
  'larissa': 'Greece', 'volos': 'Greece', 'ioannina': 'Greece',
  'chalkida': 'Greece', 'serres': 'Greece', 'alexandroupoli': 'Greece',
  'xanthi': 'Greece', 'kavala': 'Greece', 'drama': 'Greece', 'katerini': 'Greece',
  'corfu': 'Greece', 'kerkyra': 'Greece',
  'rhodes': 'Greece', 'rodos': 'Greece',
  'mykonos': 'Greece', 'santorini': 'Greece', 'thira': 'Greece',
  'crete': 'Greece', 'kriti': 'Greece', 'kos': 'Greece',
  'zakynthos': 'Greece', 'kefalonia': 'Greece', 'lefkada': 'Greece',
  'chania': 'Greece', 'rethymno': 'Greece', 'agios nikolaos': 'Greece',
  'glyfada': 'Greece', 'maroussi': 'Greece', 'kifisia': 'Greece',
  'paros': 'Greece', 'naxos': 'Greece', 'samos': 'Greece', 'halkidiki': 'Greece',

  // ── Turkey ────────────────────────────────────────────────────────────────
  'istanbul': 'Turkey', 'İstanbul': 'Turkey',
  'ankara': 'Turkey', 'izmir': 'Turkey', 'İzmir': 'Turkey',
  'bursa': 'Turkey', 'adana': 'Turkey', 'antalya': 'Turkey',
  'konya': 'Turkey', 'gaziantep': 'Turkey', 'mersin': 'Turkey',
  'diyarbakir': 'Turkey', 'kayseri': 'Turkey', 'eskisehir': 'Turkey',
  'denizli': 'Turkey', 'samsun': 'Turkey', 'trabzon': 'Turkey',
  'malatya': 'Turkey', 'alanya': 'Turkey', 'side': 'Turkey',
  'bodrum': 'Turkey', 'marmaris': 'Turkey', 'fethiye': 'Turkey',
  'dalaman': 'Turkey', 'kusadasi': 'Turkey', 'cesme': 'Turkey',
  'cappadocia': 'Turkey', 'kapadokya': 'Turkey',

  // ── Germany ───────────────────────────────────────────────────────────────
  'berlin': 'Germany', 'hamburg': 'Germany',
  'munich': 'Germany', 'münchen': 'Germany', 'muenchen': 'Germany',
  'cologne': 'Germany', 'koeln': 'Germany', 'köln': 'Germany',
  'frankfurt': 'Germany', 'stuttgart': 'Germany',
  'dusseldorf': 'Germany', 'düsseldorf': 'Germany',
  'dortmund': 'Germany', 'essen': 'Germany', 'leipzig': 'Germany',
  'Bremen': 'Germany', 'dresden': 'Germany', 'hannover': 'Germany',
  'nuremberg': 'Germany', 'nürnberg': 'Germany',
  'duisburg': 'Germany', 'bochum': 'Germany', 'wuppertal': 'Germany',
  'bielefeld': 'Germany', 'mannheim': 'Germany', 'bonn': 'Germany',

  // ── Austria ───────────────────────────────────────────────────────────────
  'vienna': 'Austria', 'wien': 'Austria',
  'graz': 'Austria', 'linz': 'Austria', 'salzburg': 'Austria',
  'innsbruck': 'Austria', 'klagenfurt': 'Austria', 'wels': 'Austria',

  // ── Switzerland ───────────────────────────────────────────────────────────
  'zurich': 'Switzerland', 'zürich': 'Switzerland',
  'geneva': 'Switzerland', 'genève': 'Switzerland', 'genf': 'Switzerland',
  'basel': 'Switzerland', 'bern': 'Switzerland', 'lausanne': 'Switzerland',
  'lucerne': 'Switzerland', 'luzern': 'Switzerland',
  'winterthur': 'Switzerland', 'st gallen': 'Switzerland', 'stgallen': 'Switzerland',

  // ── Italy ─────────────────────────────────────────────────────────────────
  'rome': 'Italy', 'roma': 'Italy',
  'milan': 'Italy', 'milano': 'Italy',
  'naples': 'Italy', 'napoli': 'Italy',
  'turin': 'Italy', 'torino': 'Italy',
  'palermo': 'Italy', 'genoa': 'Italy', 'genova': 'Italy',
  'bologna': 'Italy', 'florence': 'Italy', 'firenze': 'Italy',
  'bari': 'Italy', 'catania': 'Italy',
  'venice': 'Italy', 'venezia': 'Italy',
  'verona': 'Italy', 'trieste': 'Italy', 'messina': 'Italy',
  'padua': 'Italy', 'padova': 'Italy', 'brescia': 'Italy',
  'prato': 'Italy', 'reggio calabria': 'Italy', 'modena': 'Italy',
  'reggio emilia': 'Italy', 'perugia': 'Italy', 'ravenna': 'Italy',
  'livorno': 'Italy', 'cagliari': 'Italy', 'rimini': 'Italy',
  'siena': 'Italy', 'pisa': 'Italy', 'amalfi': 'Italy', 'positano': 'Italy',
  'sardinia': 'Italy', 'sardegna': 'Italy', 'sicily': 'Italy', 'sicilia': 'Italy',

  // ── France ────────────────────────────────────────────────────────────────
  'paris': 'France', 'marseille': 'France', 'lyon': 'France',
  'toulouse': 'France', 'nice': 'France', 'nantes': 'France',
  'montpellier': 'France', 'strasbourg': 'France', 'bordeaux': 'France',
  'lille': 'France', 'rennes': 'France', 'reims': 'France',
  'saint etienne': 'France', 'toulon': 'France', 'grenoble': 'France',
  'dijon': 'France', 'cannes': 'France',
  'antibes': 'France', 'saint tropez': 'France', 'biarritz': 'France',

  // ── Monaco ────────────────────────────────────────────────────────────────
  'monaco': 'Monaco',

  // ── Spain ─────────────────────────────────────────────────────────────────
  'madrid': 'Spain', 'barcelona': 'Spain', 'valencia': 'Spain',
  'seville': 'Spain', 'sevilla': 'Spain', 'zaragoza': 'Spain',
  'malaga': 'Spain', 'málaga': 'Spain', 'murcia': 'Spain',
  'palma': 'Spain', 'palma de mallorca': 'Spain', 'bilbao': 'Spain',
  'alicante': 'Spain', 'valladolid': 'Spain',
  'cordoba': 'Spain', 'córdoba': 'Spain', 'vigo': 'Spain',
  'granada': 'Spain', 'elche': 'Spain', 'oviedo': 'Spain',
  'santander': 'Spain', 'marbella': 'Spain', 'ibiza': 'Spain',
  'tenerife': 'Spain', 'gran canaria': 'Spain',
  'benidorm': 'Spain', 'torrevieja': 'Spain',

  // ── Portugal ──────────────────────────────────────────────────────────────
  'lisbon': 'Portugal', 'lisboa': 'Portugal',
  'porto': 'Portugal', 'braga': 'Portugal', 'setubal': 'Portugal',
  'coimbra': 'Portugal', 'funchal': 'Portugal', 'faro': 'Portugal',
  'albufeira': 'Portugal', 'lagos': 'Portugal', 'cascais': 'Portugal',
  'sintra': 'Portugal', 'amadora': 'Portugal', 'loule': 'Portugal',
  'portimao': 'Portugal',

  // ── Netherlands ───────────────────────────────────────────────────────────
  'amsterdam': 'Netherlands', 'rotterdam': 'Netherlands',
  'the hague': 'Netherlands', 'thehague': 'Netherlands', 'denhaag': 'Netherlands',
  'utrecht': 'Netherlands', 'eindhoven': 'Netherlands', 'groningen': 'Netherlands',
  'tilburg': 'Netherlands', 'almere': 'Netherlands', 'breda': 'Netherlands',
  'nijmegen': 'Netherlands', 'apeldoorn': 'Netherlands', 'haarlem': 'Netherlands',
  'arnhem': 'Netherlands', 'zaanstad': 'Netherlands',

  // ── Belgium ───────────────────────────────────────────────────────────────
  'brussels': 'Belgium', 'bruxelles': 'Belgium', 'brussel': 'Belgium',
  'antwerp': 'Belgium', 'antwerpen': 'Belgium', 'anvers': 'Belgium',
  'ghent': 'Belgium', 'gent': 'Belgium',
  'bruges': 'Belgium', 'brugge': 'Belgium',
  'liège': 'Belgium', 'liege': 'Belgium', 'namur': 'Belgium', 'leuven': 'Belgium',

  // ── Poland ────────────────────────────────────────────────────────────────
  'warsaw': 'Poland', 'warszawa': 'Poland',
  'krakow': 'Poland', 'kraków': 'Poland', 'cracow': 'Poland',
  'lodz': 'Poland', 'łódź': 'Poland',
  'wroclaw': 'Poland', 'wrocław': 'Poland',
  'poznan': 'Poland', 'poznań': 'Poland',
  'gdansk': 'Poland', 'gdańsk': 'Poland',
  'szczecin': 'Poland', 'bydgoszcz': 'Poland', 'lublin': 'Poland',
  'katowice': 'Poland', 'bialystok': 'Poland',

  // ── Czech Republic ────────────────────────────────────────────────────────
  'prague': 'Czech Republic', 'praha': 'Czech Republic',
  'brno': 'Czech Republic', 'ostrava': 'Czech Republic',
  'pilsen': 'Czech Republic', 'plzen': 'Czech Republic', 'plzeň': 'Czech Republic',
  'liberec': 'Czech Republic', 'olomouc': 'Czech Republic',

  // ── Hungary ───────────────────────────────────────────────────────────────
  'budapest': 'Hungary', 'debrecen': 'Hungary', 'szeged': 'Hungary',
  'miskolc': 'Hungary', 'pecs': 'Hungary', 'pécs': 'Hungary',
  'gyor': 'Hungary', 'győr': 'Hungary',
  'nyiregyhaza': 'Hungary', 'kecskemet': 'Hungary', 'balaton': 'Hungary',

  // ── Slovakia ──────────────────────────────────────────────────────────────
  'bratislava': 'Slovakia', 'kosice': 'Slovakia', 'košice': 'Slovakia',
  'presov': 'Slovakia', 'zilina': 'Slovakia', 'nitra': 'Slovakia',
  'banska bystrica': 'Slovakia',

  // ── United Kingdom ────────────────────────────────────────────────────────
  'london': 'United Kingdom', 'birmingham': 'United Kingdom',
  'manchester': 'United Kingdom', 'glasgow': 'United Kingdom',
  'liverpool': 'United Kingdom', 'leeds': 'United Kingdom',
  'sheffield': 'United Kingdom', 'edinburgh': 'United Kingdom',
  'bristol': 'United Kingdom', 'cardiff': 'United Kingdom',
  'leicester': 'United Kingdom', 'coventry': 'United Kingdom',
  'bradford': 'United Kingdom', 'belfast': 'United Kingdom',
  'nottingham': 'United Kingdom', 'kingston': 'United Kingdom',
  'southampton': 'United Kingdom', 'cambridge': 'United Kingdom',
  'oxford': 'United Kingdom',

  // ── Ireland ───────────────────────────────────────────────────────────────
  'dublin': 'Ireland', 'cork': 'Ireland', 'limerick': 'Ireland',
  'galway': 'Ireland', 'waterford': 'Ireland',

  // ── Nordic ────────────────────────────────────────────────────────────────
  'stockholm': 'Sweden', 'gothenburg': 'Sweden', 'göteborg': 'Sweden',
  'malmo': 'Sweden', 'malmö': 'Sweden',
  'oslo': 'Norway', 'bergen': 'Norway', 'trondheim': 'Norway', 'stavanger': 'Norway',
  'copenhagen': 'Denmark', 'københavn': 'Denmark', 'aarhus': 'Denmark', 'odense': 'Denmark',
  'helsinki': 'Finland', 'tampere': 'Finland', 'turku': 'Finland',
  'reykjavik': 'Iceland',

  // ── Eastern Europe ────────────────────────────────────────────────────────
  'kyiv': 'Ukraine', 'kiev': 'Ukraine', 'kharkiv': 'Ukraine',
  'odessa': 'Ukraine', 'lviv': 'Ukraine', 'dnipro': 'Ukraine',
  'minsk': 'Belarus',
  'chisinau': 'Moldova', 'chișinău': 'Moldova',
  'vilnius': 'Lithuania', 'riga': 'Latvia', 'tallinn': 'Estonia',
  'moscow': 'Russia', 'moskva': 'Russia',
  'saint petersburg': 'Russia', 'saintpetersburg': 'Russia',

  // ── Cyprus ────────────────────────────────────────────────────────────────
  'nicosia': 'Cyprus', 'lefkosia': 'Cyprus',
  'limassol': 'Cyprus', 'lemesos': 'Cyprus',
  'larnaca': 'Cyprus', 'paphos': 'Cyprus', 'famagusta': 'Cyprus',
  'protaras': 'Cyprus', 'ayia napa': 'Cyprus', 'ayianapa': 'Cyprus',

  // ── Malta ─────────────────────────────────────────────────────────────────
  'valletta': 'Malta', 'sliema': 'Malta',
  'st julians': 'Malta', 'stjulians': 'Malta',

  // ── UAE / Middle East ─────────────────────────────────────────────────────
  'dubai': 'UAE', 'abu dhabi': 'UAE', 'abudhabi': 'UAE', 'sharjah': 'UAE',
  'riyadh': 'Saudi Arabia', 'doha': 'Qatar',
  'beirut': 'Lebanon', 'amman': 'Jordan',

  // ── Americas ──────────────────────────────────────────────────────────────
  'new york': 'United States', 'newyork': 'United States', 'nyc': 'United States',
  'los angeles': 'United States', 'losangeles': 'United States',
  'chicago': 'United States', 'houston': 'United States', 'phoenix': 'United States',
  'philadelphia': 'United States', 'san antonio': 'United States',
  'san diego': 'United States', 'dallas': 'United States', 'san jose': 'United States',
  'miami': 'United States', 'atlanta': 'United States', 'boston': 'United States',
  'seattle': 'United States', 'denver': 'United States', 'las vegas': 'United States',
  'washington': 'United States', 'nashville': 'United States', 'orlando': 'United States',
  'toronto': 'Canada', 'montreal': 'Canada', 'montréal': 'Canada',
  'vancouver': 'Canada', 'calgary': 'Canada', 'edmonton': 'Canada',
  'ottawa': 'Canada', 'winnipeg': 'Canada', 'quebec city': 'Canada',

  // ── Australia ─────────────────────────────────────────────────────────────
  'sydney': 'Australia', 'melbourne': 'Australia', 'brisbane': 'Australia',
  'perth': 'Australia', 'adelaide': 'Australia', 'canberra': 'Australia',
  'gold coast': 'Australia',
};
